# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
  db_driver: orm
  mappings:
    biens_image:
      uri_prefix: /images_safer/biens
      upload_destination: "%kernel.project_dir%/public/images_safer/biens"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
    user_profil_image:
      uri_prefix: /images_safer/user_profil
      upload_destination: "%kernel.project_dir%/public/images_safer/user_profil"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
